version: "3.8"

services:
  earth:
    image: dataset-earth
    ports:
      - "5050:5050"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/home/python"
    environment:
      FLASK_APP: /home/python/earth/app.py
      FLASK_ENV: development
      FLASK_RUN_PORT: 5050
      FLASK_RUN_HOST: "0.0.0.0"
      CATALOG_FOLDER: "/home/python/tests"
