version: "3.8"

services:

  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db

  earth:
    image: dataset-earth
    ports:
      - "5050:5050"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/home/python"
    environment:
      FLASK_APP: /home/python/earth/app.py
      FLASK_ENV: development
      FLASK_RUN_PORT: 5050
      FLASK_RUN_HOST: "0.0.0.0"
      CATALOG_FOLDER: "/home/python/tests"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    depends_on:
      - db
